table dim_products
	lineageTag: f6b58884-0ea8-563b-bfa1-41553ed67552

	column product_id
		dataType: string
		lineageTag: 66f12080-939e-59b6-b777-4c147c09f652
		summarizeBy: none
		sourceColumn: product_id

	column product_name
		dataType: string
		lineageTag: 1706c4d9-ce3a-5616-bbc4-56fa6a892088
		summarizeBy: none
		sourceColumn: product_name

	column category
		dataType: string
		lineageTag: 219d00ae-3d08-526f-a093-8a53c3bb4351
		summarizeBy: none
		sourceColumn: category

	column unit_cost
		dataType: double
		lineageTag: c41e1a9e-beba-534d-be4d-a88692a21e06
		summarizeBy: none
		sourceColumn: unit_cost

	column unit_price
		dataType: double
		lineageTag: 20208252-6ba6-56fd-a22c-4eb49bfc3822
		summarizeBy: none
		sourceColumn: unit_price

	column lead_time_days
		dataType: int64
		lineageTag: d3a0c259-adff-5f48-bf43-6105fe52600f
		summarizeBy: none
		sourceColumn: lead_time_days

	partition dim_products = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\dim_products.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"product_id", type text}, {"product_name", type text}, {"category", type text}, {"unit_cost", type number}, {"unit_price", type number}, {"lead_time_days", Int64.Type}}, "en-US")
				in
				    Typed
