table dim_warehouses
	lineageTag: 68d84430-7857-50bb-afd4-490b79de51b7

	column warehouse_id
		dataType: string
		lineageTag: f50602f7-307d-5a1c-b4e8-5ac71d7d15a7
		summarizeBy: none
		sourceColumn: warehouse_id

	column warehouse_name
		dataType: string
		lineageTag: c4761547-47c2-5cd2-ae87-cd5798adf289
		summarizeBy: none
		sourceColumn: warehouse_name

	column region
		dataType: string
		lineageTag: 73658c62-ea00-511a-a101-3e95ff46b1b0
		summarizeBy: none
		sourceColumn: region

	partition dim_warehouses = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\dim_warehouses.csv"), [Delimiter=",", Encoding=65001, QuoteStyle=QuoteStyle.Csv]),
				    Promoted = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    Typed = Table.TransformColumnTypes(Promoted, {{"warehouse_id", type text}, {"warehouse_name", type text}, {"region", type text}}, "en-US")
				in
				    Typed
